/*
 * DiABluCR.java
 *
 * Created on 18 de Abril de 2006, 11:00
 *
 * Copyright (C) 2006 CITAR
 * This is part of the DiABlu Project
 * http://diablu.jorgecardoso.org
 * Created by Jorge Cardoso(jccardoso@porto.ucp.pt) & Nuno Rodrigues(nunoalexandre.rodrigues@gmail.com)
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation; either version 2 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 * MA 02111-1307 USA
 */

package citar.diablu.gui;

/**
 *
 * @author  nrodrigues
 */
public class DiABluCR extends javax.swing.JDialog {
    
    /**
     * Creates new form DiABluCR
     */
    public DiABluCR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        about_jp = new javax.swing.JPanel();
        development_jl = new javax.swing.JLabel();
        citar_jl = new javax.swing.JLabel();
        version_jl1 = new javax.swing.JLabel();
        development_jl1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About DiABlu Scout");
        development_jl.setText("A project by Jorge Cardoso");

        citar_jl.setText("CITAR - Research Center for Science and Technology  in Art");

        version_jl1.setText("DiABlu Scout version 0.99");

        development_jl1.setText("with development by Nuno Rodrigues, Jorge Cardoso");

        org.jdesktop.layout.GroupLayout about_jpLayout = new org.jdesktop.layout.GroupLayout(about_jp);
        about_jp.setLayout(about_jpLayout);
        about_jpLayout.setHorizontalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(version_jl1)
                    .add(development_jl))
                .addContainerGap(370, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, about_jpLayout.createSequentialGroup()
                .addContainerGap(209, Short.MAX_VALUE)
                .add(citar_jl)
                .addContainerGap())
            .add(about_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(development_jl1)
                .addContainerGap(246, Short.MAX_VALUE))
        );
        about_jpLayout.setVerticalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(version_jl1)
                .add(31, 31, 31)
                .add(development_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(development_jl1)
                .add(91, 91, 91)
                .add(citar_jl)
                .add(32, 32, 32))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiABluCR(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about_jp;
    private javax.swing.JLabel citar_jl;
    private javax.swing.JLabel development_jl;
    private javax.swing.JLabel development_jl1;
    private javax.swing.JLabel version_jl1;
    // End of variables declaration//GEN-END:variables
    
}
