/*
 * NewJFrame.java
 *
 * Created on 23 de Janeiro de 2007, 0:14
 */

package pt.citar.diablu.legosc;

import java.io.IOException;

/**
 *
 * @author  Jorge Cardoso
 */
public class LegOSCView extends javax.swing.JFrame implements LegOSCObserver {
    
    LegOSC legOSC;
    
    boolean legOSCStarted;
    
    /** Creates new form NewJFrame */
    public LegOSCView() {
        initComponents();
        
        legOSCStarted = false;
        legOSC = new LegOSC();
        legOSC.registerObserver(this);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tfLocalPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTargetAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTargetPort = new javax.swing.JTextField();
        btnStartStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taLog = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        tfCommPort = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        tfLocalPort.setText("10000");
        tfLocalPort.setToolTipText("The port on which LegOSC is listening for OSC commands.");
        getContentPane().add(tfLocalPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 50, -1));

        jLabel1.setText("Local Port:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Target Address:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tfTargetAddress.setText("localhost");
        tfTargetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTargetAddressActionPerformed(evt);
            }
        });

        getContentPane().add(tfTargetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        jLabel3.setText("Target Port:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        tfTargetPort.setText("20000");
        getContentPane().add(tfTargetPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btnStartStop.setText("Start");
        btnStartStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStartStopMousePressed(evt);
            }
        });

        getContentPane().add(btnStartStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        taLog.setColumns(20);
        taLog.setRows(5);
        jScrollPane1.setViewportView(taLog);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 440, 140));

        jLabel4.setText("Log:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        tfCommPort.setText("COM16");
        getContentPane().add(tfCommPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 50, -1));

        jLabel5.setText("Brick Com Port");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        legOSC.stop(); 
    }//GEN-LAST:event_formWindowClosed

    private void btnStartStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartStopMousePressed
        // TODO add your handling code here:
        if (legOSCStarted) {
            legOSC.stop();
            legOSCStarted = false;
            btnStartStop.setText("Start");
            
        } else {            
            int localPort = 10000;
            int remotePort = 20000;
            try {                
                localPort = Integer.parseInt(tfLocalPort.getText());
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
            }
            try {
                remotePort = Integer.parseInt(tfTargetPort.getText());
            } catch (NumberFormatException ex) {
                ex.printStackTrace();
            }
               
            if (legOSC.start(tfCommPort.getText(), localPort, tfTargetAddress.getText(), remotePort)) {
                legOSCStarted = true;
                btnStartStop.setText("Stop");
                taLog.append("Server started! Ok to receive commands.\n");
            }
        }
        
    }//GEN-LAST:event_btnStartStopMousePressed
    public void error(String error) {
        System.err.println(error);
        //taLog.append("Error: " + error + "\n");
    }
    public void message(String message) {
        //taLog.append("Message: " + message + "\n");
        System.err.println(message);
    }
    
    private void tfTargetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTargetAddressActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_tfTargetAddressActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LegOSCView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taLog;
    private javax.swing.JTextField tfCommPort;
    private javax.swing.JTextField tfLocalPort;
    private javax.swing.JTextField tfTargetAddress;
    private javax.swing.JTextField tfTargetPort;
    // End of variables declaration//GEN-END:variables
    
}
