/*
 * NewJFrame.java
 *
 * Created on 23 de Janeiro de 2007, 0:14
 */

package pt.citar.diablu.legosc;

/**
 *
 * @author  Jorge Cardoso
 */
public class LegOSCView extends javax.swing.JFrame {
    
    LegOSC legOSC;
    
    boolean legOSCStarted;
    
    /** Creates new form NewJFrame */
    public LegOSCView() {
        initComponents();
        
        legOSCStarted = false;
        legOSC = new LegOSC();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        tfLocalPort = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfTargetAddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTargetPort = new javax.swing.JTextField();
        btnStartStop = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        tfLocalPort.setText("10000");
        tfLocalPort.setToolTipText("The port on which LegOSC is listening for OSC commands.");
        getContentPane().add(tfLocalPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 50, -1));

        jLabel1.setText("Local Port:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel2.setText("Target Address:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        tfTargetAddress.setText("localhost");
        tfTargetAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTargetAddressActionPerformed(evt);
            }
        });

        getContentPane().add(tfTargetAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, 120, -1));

        jLabel3.setText("Target Port:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, -1, -1));

        tfTargetPort.setText("20000");
        getContentPane().add(tfTargetPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, -1));

        btnStartStop.setText("Start");
        btnStartStop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStartStopMousePressed(evt);
            }
        });

        getContentPane().add(btnStartStop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 440, 140));

        jLabel4.setText("Log:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartStopMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStartStopMousePressed
        // TODO add your handling code here:
        if (legOSCStarted) {
            legOSC.stop();
            legOSCStarted = false;
            btnStartStop.setText("Start");
            
        } else {
            legOSC.start();
            legOSCStarted = true;
            btnStartStop.setText("Stop");
        }
        
    }//GEN-LAST:event_btnStartStopMousePressed

    private void tfTargetAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTargetAddressActionPerformed
// TODO add your handling code here:
    }//GEN-LAST:event_tfTargetAddressActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LegOSCView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnStartStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField tfLocalPort;
    private javax.swing.JTextField tfTargetAddress;
    private javax.swing.JTextField tfTargetPort;
    // End of variables declaration//GEN-END:variables
    
}
