/*
 * DiABluCR.java
 *
 * Created on 18 de Abril de 2006, 11:00
 *
 * Copyright (C) 2006 CITAR
 * This is part of the DiABlu Project
 * http://diablu.jorgecardoso.org
 * Created by Jorge Cardoso(jccardoso@porto.ucp.pt) & Nuno Rodrigues(nunoalexandre.rodrigues@gmail.com)
 *
 * This program is free software; you can redistribute it and/or modify it under the terms of the 
 * GNU General Public License as published by the Free Software Foundation; either version 2 of the 
 * License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with this program; 
 * if not, write to the Free Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, 
 * MA 02111-1307 USA
 */

package citar.diablu.gui;

/**
 *
 * @author  nrodrigues
 */
public class DiABluCR extends javax.swing.JDialog {
    
    /**
     * Creates new form DiABluCR
     */
    public DiABluCR(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        about_jp = new javax.swing.JPanel();
        development_jl = new javax.swing.JLabel();
        citar_jl = new javax.swing.JLabel();
        version_jl1 = new javax.swing.JLabel();
        development_jl1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About DiABlu Scout");
        development_jl.setText("A project by Jorge Cardoso");

        citar_jl.setText("at CITAR - Research Center for Science and Technology  in Art");

        version_jl1.setText("DiABlu Scout version 0.99");

        development_jl1.setText("with development by Nuno Rodrigues, Jorge Cardoso");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/diablufinal.gif")));

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout about_jpLayout = new org.jdesktop.layout.GroupLayout(about_jp);
        about_jp.setLayout(about_jpLayout);
        about_jpLayout.setHorizontalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .add(jLabel1)
                .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(about_jpLayout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(version_jl1)
                            .add(development_jl)
                            .add(development_jl1)
                            .add(citar_jl))
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(about_jpLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton1)
                        .addContainerGap())))
        );
        about_jpLayout.setVerticalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(version_jl1)
                .add(22, 22, 22)
                .add(development_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(development_jl1)
                .add(6, 6, 6)
                .add(citar_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(jButton1))
            .add(jLabel1)
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiABluCR(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about_jp;
    private javax.swing.JLabel citar_jl;
    private javax.swing.JLabel development_jl;
    private javax.swing.JLabel development_jl1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel version_jl1;
    // End of variables declaration//GEN-END:variables
    
}
