/*
 * DiABluServerCompactView.java
 *
 * Created on 30 de Agosto de 2006, 1:53
 */

package citar.diablu.server.view.main.compact;

// J2SE Classes
import java.util.Vector;

// j2se 1.5 - DiABlu System Constants
import static citar.diablu.server.model.settings.DiABluServerCONSTANTS.*;

/*
 * ALL DiABlu Data Classes
 */
import citar.diablu.server.model.data.*;

// i18n & l9n
import java.util.ResourceBundle;

// Swing
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.ListSelectionEvent;

// logger
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.logging.Handler;
import java.util.logging.LogRecord;
import citar.diablu.server.model.log.diABluLogHandler;

// model
import citar.diablu.server.controller.out.view.DiABluServerViewModelListener;

// controller
import citar.diablu.server.controller.in.view.DiABluServerViewControllerListener;

/**
 *
 * @author  Nuno Rodrigues
 */
public class DiABluServerCompactView extends javax.swing.JFrame implements DiABluServerViewModelListener {
    
    // our controller interface
    private DiABluServerViewControllerListener dController = null;
    
    // log
    private static Logger logger = Logger.getLogger(LOG_MAIN_NAME); // Log API
    
    // i18n resource bundle
    ResourceBundle viewBundle;
    
    /** Creates new form DiABluServerCompactView */
    public DiABluServerCompactView(DiABluServerViewControllerListener dC) {
        
        this.dController = dC;
        initComponents();
        logger.config("STARTING COMPAKT VIEW");
        this.setVisible(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        AllPane = new javax.swing.JTabbedPane();
        detected_jp = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        detected_jsp = new javax.swing.JScrollPane();
        detectedTable_jt = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        settings_jp = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        delay_jtf = new javax.swing.JTextField();
        delay_jl = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        vCycles_jl1 = new javax.swing.JLabel();
        vCycles_jtf = new javax.swing.JTextField();
        vCycles_jl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        service_jtf = new javax.swing.JTextField();
        service_jl = new javax.swing.JLabel();
        serviceDescription_jtf = new javax.swing.JTextField();
        serviceDescription_jl = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jCheckBox2 = new javax.swing.JCheckBox();
        output_jp = new javax.swing.JPanel();
        address_jtf = new javax.swing.JTextField();
        adress_jl = new javax.swing.JLabel();
        port_jtf = new javax.swing.JTextField();
        port_jl = new javax.swing.JLabel();
        localhost_jb = new javax.swing.JButton();
        log_jp = new javax.swing.JPanel();
        log_jsp = new javax.swing.JScrollPane();
        log_jta = new javax.swing.JTextArea();
        clearLog_jb = new javax.swing.JButton();
        saveLog_jb = new javax.swing.JButton();
        logDetail_jl = new javax.swing.JLabel();
        logDetail_jcb = new javax.swing.JComboBox();
        menubar_jmb = new javax.swing.JMenuBar();
        settings_jm = new javax.swing.JMenu();
        loadSettings_jmi = new javax.swing.JMenuItem();
        saveSettings_jmi = new javax.swing.JMenuItem();
        language_jm = new javax.swing.JMenu();
        languagePT_jmi = new javax.swing.JMenuItem();
        languageFR_jmi = new javax.swing.JMenuItem();
        languageEN_jmi = new javax.swing.JMenuItem();
        location_jm = new javax.swing.JMenu();
        locationPT_jmi = new javax.swing.JMenuItem();
        locationFR_jmi = new javax.swing.JMenuItem();
        locationEN_jmi = new javax.swing.JMenuItem();
        blackList_jm = new javax.swing.JMenu();
        addBlackList_jmi = new javax.swing.JMenuItem();
        removeBlackList_jmi = new javax.swing.JMenuItem();
        resetBlackList_jmi = new javax.swing.JMenuItem();
        exit_jm = new javax.swing.JMenu();
        exit_jmi = new javax.swing.JMenuItem();
        credits_jm = new javax.swing.JMenu();
        credits_jmi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        detected_jp.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        detected_jsp.setName("DetectedTab");
        detectedTable_jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UUID  ", "Friendly Name", "Device Type", "Status", "Last Msg", "Last Key"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        detectedTable_jt.getColumnModel().getColumn(0).setPreferredWidth(310);
        detectedTable_jt.getColumnModel().getColumn(1).setPreferredWidth(400);
        detectedTable_jt.getColumnModel().getColumn(2).setPreferredWidth(80);
        detectedTable_jt.getColumnModel().getColumn(3).setPreferredWidth(120);
        //detectedTable_jt.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //Ask to be notified of selection changes.
        ListSelectionModel rowSM = detectedTable_jt.getSelectionModel();
        rowSM.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //Ignore extra messages.
                if (e.getValueIsAdjusting()) return;

                ListSelectionModel lsm =
                (ListSelectionModel)e.getSource();
                if (lsm.isSelectionEmpty()) {
                    //no rows are selected
                } else {
                    int selectedRow = lsm.getMinSelectionIndex();

                    //selectedRow is selected
                    String uuidT = detectedTable_jt.getValueAt(selectedRow,0).toString();
                    String fName = detectedTable_jt.getValueAt(selectedRow,1).toString();
                    DiABluID dId = new DiABluID(uuidT,fName);
                    dController.newSelectedDevice(dId);

                }
            }
        });
        detected_jsp.setViewportView(detectedTable_jt);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detected_jsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(detected_jsp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 156, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Filter"));
        jCheckBox4.setText("Filter devices with friendly name not set");
        jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jButton3.setText("Reset");

        jButton4.setText("Remove");

        jButton5.setText("Add");

        jLabel1.setText("Black List:");

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jCheckBox4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 205, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jButton3)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jCheckBox4)
                    .add(jButton3)
                    .add(jButton4)
                    .add(jButton5)
                    .add(jLabel1))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout detected_jpLayout = new org.jdesktop.layout.GroupLayout(detected_jp);
        detected_jp.setLayout(detected_jpLayout);
        detected_jpLayout.setHorizontalGroup(
            detected_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        detected_jpLayout.setVerticalGroup(
            detected_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(detected_jpLayout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AllPane.addTab("Detection", detected_jp);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Discovery"));
        delay_jtf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        delay_jtf.setText("10000");

        delay_jl.setText("Delay between bluetooth discoverys(ms):");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField1.setText("0");

        vCycles_jl1.setText("Verify inquirys before device entry:");

        vCycles_jtf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        vCycles_jtf.setText("2");

        vCycles_jl.setText("Verify inquirys before device removal:");

        jButton1.setText("Start");

        jCheckBox1.setText("Auto Start");
        jCheckBox1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox1.setMargin(new java.awt.Insets(0, 0, 0, 0));

        jCheckBox3.setText("FAST MODE");
        jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(vCycles_jl1)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jCheckBox3)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 339, Short.MAX_VALUE)
                                .add(vCycles_jl))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jCheckBox1)
                                .add(329, 329, 329)
                                .add(delay_jl)))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, delay_jtf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, vCycles_jtf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)))
                    .add(jButton1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(26, 26, 26)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(delay_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(delay_jl))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(vCycles_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vCycles_jl))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(vCycles_jl1)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jCheckBox3)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Service"));
        service_jtf.setText("DiABlu666");

        service_jl.setText("Service Name:");

        serviceDescription_jtf.setText("DiABlu System is in tha house :P");

        serviceDescription_jl.setText("Service Description:");

        jButton2.setText("Start");

        jCheckBox2.setText("Auto Start");
        jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jButton2)
                        .add(195, 195, 195)
                        .add(service_jl))
                    .add(jPanel2Layout.createSequentialGroup()
                        .add(jCheckBox2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(serviceDescription_jl)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, serviceDescription_jtf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE)
                    .add(service_jtf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 341, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(service_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(service_jl)
                    .add(jButton2))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(serviceDescription_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(serviceDescription_jl)
                    .add(jCheckBox2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout settings_jpLayout = new org.jdesktop.layout.GroupLayout(settings_jp);
        settings_jp.setLayout(settings_jpLayout);
        settings_jpLayout.setHorizontalGroup(
            settings_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        settings_jpLayout.setVerticalGroup(
            settings_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(settings_jpLayout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        AllPane.addTab("Bluetooth", settings_jp);

        address_jtf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        address_jtf.setText("127.0.0.1");

        adress_jl.setText("Target Address:");

        port_jtf.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        port_jtf.setText("10000");

        port_jl.setText("Port:");

        localhost_jb.setText("Localhost");

        org.jdesktop.layout.GroupLayout output_jpLayout = new org.jdesktop.layout.GroupLayout(output_jp);
        output_jp.setLayout(output_jpLayout);
        output_jpLayout.setHorizontalGroup(
            output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(output_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(port_jl)
                    .add(adress_jl))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(port_jtf)
                    .add(address_jtf, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(localhost_jb)
                .addContainerGap(439, Short.MAX_VALUE))
        );
        output_jpLayout.setVerticalGroup(
            output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(output_jpLayout.createSequentialGroup()
                .add(29, 29, 29)
                .add(output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(adress_jl)
                    .add(address_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(localhost_jb))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(output_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(port_jl)
                    .add(port_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(157, Short.MAX_VALUE))
        );
        AllPane.addTab("Open Sound Control", output_jp);

        log_jta.setColumns(20);
        log_jta.setRows(5);
        log_jsp.setViewportView(log_jta);

        clearLog_jb.setText("Clear ");
        clearLog_jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearLog_jbActionPerformed(evt);
            }
        });

        saveLog_jb.setText("Save");
        saveLog_jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveLog_jbActionPerformed(evt);
            }
        });

        logDetail_jl.setText("Log Detail:");

        logDetail_jcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Simple", "Detailed", "Debug" }));
        logDetail_jcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logDetail_jcbActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout log_jpLayout = new org.jdesktop.layout.GroupLayout(log_jp);
        log_jp.setLayout(log_jpLayout);
        log_jpLayout.setHorizontalGroup(
            log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(log_jpLayout.createSequentialGroup()
                .add(log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(log_jpLayout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(logDetail_jl)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(logDetail_jcb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 414, Short.MAX_VALUE)
                        .add(clearLog_jb)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(saveLog_jb))
                    .add(log_jpLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(log_jsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)))
                .addContainerGap())
        );
        log_jpLayout.setVerticalGroup(
            log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, log_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(log_jsp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 160, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 30, Short.MAX_VALUE)
                .add(log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(saveLog_jb)
                        .add(clearLog_jb))
                    .add(log_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(logDetail_jl)
                        .add(logDetail_jcb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        AllPane.addTab("Log", log_jp);

        AllPane.getAccessibleContext().setAccessibleName("Settings");

        settings_jm.setText("Settings");
        loadSettings_jmi.setText("Load Settings");
        settings_jm.add(loadSettings_jmi);

        saveSettings_jmi.setText("Save settings");
        settings_jm.add(saveSettings_jmi);

        language_jm.setText("Language");
        languagePT_jmi.setText("Portugu\u00eas");
        language_jm.add(languagePT_jmi);

        languageFR_jmi.setText("Fran\u00e7ais");
        language_jm.add(languageFR_jmi);

        languageEN_jmi.setText("English");
        language_jm.add(languageEN_jmi);

        settings_jm.add(language_jm);

        location_jm.setText("Menu");
        locationPT_jmi.setText("Item");
        location_jm.add(locationPT_jmi);

        locationFR_jmi.setText("Item");
        location_jm.add(locationFR_jmi);

        locationEN_jmi.setText("Item");
        location_jm.add(locationEN_jmi);

        settings_jm.add(location_jm);

        menubar_jmb.add(settings_jm);

        blackList_jm.setText("Black List");
        addBlackList_jmi.setText("Item");
        blackList_jm.add(addBlackList_jmi);

        removeBlackList_jmi.setText("Item");
        blackList_jm.add(removeBlackList_jmi);

        resetBlackList_jmi.setText("Item");
        blackList_jm.add(resetBlackList_jmi);

        menubar_jmb.add(blackList_jm);

        exit_jm.setText("Exit");
        exit_jm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_jmActionPerformed(evt);
            }
        });

        exit_jmi.setText("Exit");
        exit_jmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_jmiActionPerformed(evt);
            }
        });

        exit_jm.add(exit_jmi);

        menubar_jmb.add(exit_jm);

        credits_jm.setText("Credits");
        credits_jm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credits_jmActionPerformed(evt);
            }
        });

        credits_jmi.setText("About");
        credits_jmi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                credits_jmiActionPerformed(evt);
            }
        });

        credits_jm.add(credits_jmi);

        menubar_jmb.add(credits_jm);

        setJMenuBar(menubar_jmb);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(AllPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 695, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(AllPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 260, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logDetail_jcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logDetail_jcbActionPerformed
  
    }//GEN-LAST:event_logDetail_jcbActionPerformed

    private void saveLog_jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveLog_jbActionPerformed
        
        logger.fine("[Controller]Save Settings");
        dController.saveSettings();
        
    }//GEN-LAST:event_saveLog_jbActionPerformed

    private void clearLog_jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearLog_jbActionPerformed
        
        dController.clearLog();
        logger.fine("[Controller]Clear Log");
        
    }//GEN-LAST:event_clearLog_jbActionPerformed

    private void exit_jmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_jmActionPerformed
        logger.fine("[Controller]Exit the DiABlu System");
        dController.exit();
    }//GEN-LAST:event_exit_jmActionPerformed

    private void exit_jmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_jmiActionPerformed
// TODO:remove this method
    }//GEN-LAST:event_exit_jmiActionPerformed

    private void credits_jmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credits_jmActionPerformed
        
        logger.fine("[Controller]Show Credits");
        dController.showCredits();
        
    }//GEN-LAST:event_credits_jmActionPerformed

    private void credits_jmiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_credits_jmiActionPerformed
// TODO add your handling code here:
        // TODO: remove this method
    }//GEN-LAST:event_credits_jmiActionPerformed
    
 
    // Protocol Bluetooth
    public void setFilterFNames(boolean filterFN){}
    
    public void setServiceName(String newServiceName){}
    
    public void setServiceDescription(String newServiceDesc){}
    
    public void setBluetoothDelay(int delay){}
    
    public void setAutoDiscovery(boolean autoDisc){}
    
    public void setAutoService(boolean autoService){}
    
    public void setFastMode(boolean fastmode){}     
    
    public void setDiscoveryStatus(boolean started){}
    
    public void setServiceStatus(boolean started){}
    
    public void setSimulatorStatus(boolean started){}
    
    public void setVCyclesIN(int vcIN){}
    
    public void setVCyclesOUT(int vcOUT){}
    
    public void setProtocol(String prot){}
    
    // blacklist
    /**
     * This method tells the view to reset it's 
     * detected devices table and fill up with
     * new values
     * @param Vector <DiABluDevice> newList
     *
     */
    public void resetDeviceList(Vector <DiABluDevice> ddList){}
    
    // Global
    public void setCountry(String country){}
    
    public void setLanguage(String language){}
    
    // Log     
    public void log(int priority, String log){}
    
    public void setLogDetail(int priority){}
    
    public void clearLog(){}
    
    // Simulator    
    public void setSimulatorAuto(boolean auto){}
    
    public void simulatorIsRunning(boolean status){}
    
    // Hide/unhide
    public void setVisibleView(boolean visible){}
    
        /* 
     * DiABlu Device's
     *
     */   
    public void newDiABluDevices (Vector <DiABluDevice> addDiABlus){}
    
    public void editDiABluDevices (Vector <DiABluDevice> editDiABlus){}
    
    public void removeDiABluDevices (Vector <DiABluDevice> removeDiABlus){}
    
    public void newMsg (DiABluMsg newMsg){}
    
    public void newKey (DiABluKey newKey){}
    
    /* 
     * Settings
     */
    
    // Global    
    public void setResourceBundle(ResourceBundle rb){}
    
    // Log
    /**
     *  Set's the log level
     *
     */
    public void setLogLevel(Level newLevel){}
    
    
    
    // Input
    // TODO:Multiple Protocol
   
    // Output
    // Protocol OpenSoundControl
    public void setTargetAddress(String targetURL){}
    
    public void setTargetPort(String targetPort){}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane AllPane;
    private javax.swing.JMenuItem addBlackList_jmi;
    private javax.swing.JTextField address_jtf;
    private javax.swing.JLabel adress_jl;
    private javax.swing.JMenu blackList_jm;
    private javax.swing.JButton clearLog_jb;
    private javax.swing.JMenu credits_jm;
    private javax.swing.JMenuItem credits_jmi;
    private javax.swing.JLabel delay_jl;
    private javax.swing.JTextField delay_jtf;
    private javax.swing.JTable detectedTable_jt;
    private javax.swing.JPanel detected_jp;
    private javax.swing.JScrollPane detected_jsp;
    private javax.swing.JMenu exit_jm;
    private javax.swing.JMenuItem exit_jmi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JMenuItem languageEN_jmi;
    private javax.swing.JMenuItem languageFR_jmi;
    private javax.swing.JMenuItem languagePT_jmi;
    private javax.swing.JMenu language_jm;
    private javax.swing.JMenuItem loadSettings_jmi;
    private javax.swing.JButton localhost_jb;
    private javax.swing.JMenuItem locationEN_jmi;
    private javax.swing.JMenuItem locationFR_jmi;
    private javax.swing.JMenuItem locationPT_jmi;
    private javax.swing.JMenu location_jm;
    private javax.swing.JComboBox logDetail_jcb;
    private javax.swing.JLabel logDetail_jl;
    private javax.swing.JPanel log_jp;
    private javax.swing.JScrollPane log_jsp;
    private javax.swing.JTextArea log_jta;
    private javax.swing.JMenuBar menubar_jmb;
    private javax.swing.JPanel output_jp;
    private javax.swing.JLabel port_jl;
    private javax.swing.JTextField port_jtf;
    private javax.swing.JMenuItem removeBlackList_jmi;
    private javax.swing.JMenuItem resetBlackList_jmi;
    private javax.swing.JButton saveLog_jb;
    private javax.swing.JMenuItem saveSettings_jmi;
    private javax.swing.JLabel serviceDescription_jl;
    public javax.swing.JTextField serviceDescription_jtf;
    private javax.swing.JLabel service_jl;
    private javax.swing.JTextField service_jtf;
    private javax.swing.JMenu settings_jm;
    private javax.swing.JPanel settings_jp;
    private javax.swing.JLabel vCycles_jl;
    private javax.swing.JLabel vCycles_jl1;
    private javax.swing.JTextField vCycles_jtf;
    // End of variables declaration//GEN-END:variables
    
}
