/*
 * DiABluCreditsView.java
 *
 * Created on 18 de Abril de 2006, 11:00
 */

package citar.diablu.server.view.shared.dialogs.credits;

/**
 *
 * @author  nrodrigues
 */
public class DiABluServerCreditsDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form DiABluCreditsView
     */
    public DiABluServerCreditsDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        about_jp = new javax.swing.JPanel();
        ds_jl = new javax.swing.JLabel();
        version_jl = new javax.swing.JLabel();
        development_jl = new javax.swing.JLabel();
        citar_jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("About_DiABlu_Server"));
        ds_jl.setFont(new java.awt.Font(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("Tahoma"), 1, 36));
        ds_jl.setForeground(java.awt.Color.blue);
        ds_jl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ds_jl.setText(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("DiABlu_Server"));

        version_jl.setText(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("Beta_Version_1"));

        development_jl.setText(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("Development:_Jorge_Cardoso,_Nuno_Rodrigues"));

        citar_jl.setText(java.util.ResourceBundle.getBundle("citar/diablu/server/ressources/defaultBundle").getString("CITAR"));

        org.jdesktop.layout.GroupLayout about_jpLayout = new org.jdesktop.layout.GroupLayout(about_jp);
        about_jp.setLayout(about_jpLayout);
        about_jpLayout.setHorizontalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(about_jpLayout.createSequentialGroup()
                        .add(ds_jl, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(about_jpLayout.createSequentialGroup()
                        .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(version_jl)
                            .add(citar_jl)
                            .add(development_jl))
                        .add(135, 135, 135))))
        );
        about_jpLayout.setVerticalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .add(ds_jl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 125, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(version_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(citar_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(development_jl)
                .add(42, 42, 42))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 227, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiABluServerCreditsDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about_jp;
    private javax.swing.JLabel citar_jl;
    private javax.swing.JLabel development_jl;
    private javax.swing.JLabel ds_jl;
    private javax.swing.JLabel version_jl;
    // End of variables declaration//GEN-END:variables
    
}
