/*
 * DiABluCreditsView.java
 *
 * Created on 18 de Abril de 2006, 11:00
 */

package citar.diablu.server.view.shared.dialogs.credits;

/**
 *
 * @author  nrodrigues
 */
public class DiABluServerCreditsDialog extends javax.swing.JDialog {
    
    /**
     * Creates new form DiABluCreditsView
     */
    public DiABluServerCreditsDialog(java.awt.Frame parent, boolean modal) {
        super(parent,modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        about_jp = new javax.swing.JPanel();
        diabluLogo_jl = new javax.swing.JLabel();
        version_jl = new javax.swing.JLabel();
        pLeader_jl = new javax.swing.JLabel();
        citar_jl = new javax.swing.JLabel();
        developer_jl = new javax.swing.JLabel();
        homepage_jl = new javax.swing.JLabel();
        svn_jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About DiABlu Server");
        setAlwaysOnTop(true);
        setName("creditsWindow_d");
        setResizable(false);
        about_jp.setMaximumSize(new java.awt.Dimension(300, 700));
        about_jp.setOpaque(false);
        about_jp.setPreferredSize(new java.awt.Dimension(700, 300));
        diabluLogo_jl.setIcon(new javax.swing.ImageIcon("D:\\Engenharia\\Projectos\\DiABlu Project\\Working Copy\\citar\\logo-trans1.png"));

        version_jl.setText("Codename: Scout");

        pLeader_jl.setText("Project Leader: Jorge Cardoso (jccardoso@porto.ucp.pt)");

        citar_jl.setText("Research Center of Cience and Technology for Art (http://artes.ucp.pt/citar/) ");

        developer_jl.setText("System Development: Nuno Rodrigues (nunoalexandre.rodrigues@gmail.com)");

        homepage_jl.setText("Homepage: http://diablu.jorgecardoso.org");

        svn_jl.setText("SVN Server: http://code.google.com/p/diablu/");

        org.jdesktop.layout.GroupLayout about_jpLayout = new org.jdesktop.layout.GroupLayout(about_jp);
        about_jp.setLayout(about_jpLayout);
        about_jpLayout.setHorizontalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(diabluLogo_jl)
                    .add(about_jpLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(version_jl)
                            .add(homepage_jl)
                            .add(pLeader_jl)
                            .add(developer_jl)
                            .add(svn_jl)
                            .add(citar_jl))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        about_jpLayout.setVerticalGroup(
            about_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jpLayout.createSequentialGroup()
                .add(diabluLogo_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(version_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(citar_jl, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(svn_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(homepage_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(pLeader_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(developer_jl)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 476, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(about_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 431, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiABluServerCreditsDialog(new javax.swing.JFrame(), true).setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel about_jp;
    private javax.swing.JLabel citar_jl;
    private javax.swing.JLabel developer_jl;
    private javax.swing.JLabel diabluLogo_jl;
    private javax.swing.JLabel homepage_jl;
    private javax.swing.JLabel pLeader_jl;
    private javax.swing.JLabel svn_jl;
    private javax.swing.JLabel version_jl;
    // End of variables declaration//GEN-END:variables
    
}
