/*
 * DiABluScoutView.java
 *
 * Created on 5 de Setembro de 2006, 23:15
 */

package citar.diablu.scout.view;

/**
 *
 * @author  Nuno Rodrigues
 */
public class DiABluScoutView extends javax.swing.JFrame {
    
    /** Creates new form DiABluScoutView */
    public DiABluScoutView() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        main_jp = new javax.swing.JPanel();
        anchor_jp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        search_jb = new javax.swing.JToggleButton();
        automatic = new javax.swing.JCheckBox();
        delay_jtf = new javax.swing.JTextField();
        ms_jl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        landmark_jp = new javax.swing.JPanel();
        anchor_jsp = new javax.swing.JScrollPane();
        anchor_jt = new javax.swing.JTable();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jToggleButton4 = new javax.swing.JToggleButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        menu_jmb = new javax.swing.JMenuBar();
        file_jm = new javax.swing.JMenu();
        loadScoutMap_jmi = new javax.swing.JMenuItem();
        saveScoutMap_jmi = new javax.swing.JMenuItem();
        language = new javax.swing.JMenu();
        languagePT_jmi = new javax.swing.JMenuItem();
        languageEN_jmi = new javax.swing.JMenuItem();
        help_jm = new javax.swing.JMenu();
        exit_jm = new javax.swing.JMenu();
        exitWithoutSave_jmi = new javax.swing.JMenuItem();
        exitWithSave_jmi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("DiABlu Scout Map Designer Desktop Alpha");
        main_jp.setPreferredSize(new java.awt.Dimension(600, 600));
        anchor_jp.setBorder(javax.swing.BorderFactory.createTitledBorder("Detected Anchor Points"));
        anchor_jp.setPreferredSize(new java.awt.Dimension(100, 100));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "UUID", "Friendly Name", "Device Class"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        search_jb.setText("Manual Search");

        automatic.setText("Automatic restart device inquiry every");
        automatic.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        automatic.setMargin(new java.awt.Insets(0, 0, 0, 0));

        ms_jl.setText("ms");

        org.jdesktop.layout.GroupLayout anchor_jpLayout = new org.jdesktop.layout.GroupLayout(anchor_jp);
        anchor_jp.setLayout(anchor_jpLayout);
        anchor_jpLayout.setHorizontalGroup(
            anchor_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 598, Short.MAX_VALUE)
            .add(anchor_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(search_jb)
                .add(199, 199, 199)
                .add(automatic)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(delay_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(ms_jl)
                .add(139, 139, 139))
        );
        anchor_jpLayout.setVerticalGroup(
            anchor_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(anchor_jpLayout.createSequentialGroup()
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 118, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(anchor_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(search_jb)
                    .add(automatic)
                    .add(delay_jtf, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(ms_jl))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 610, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 38, Short.MAX_VALUE)
        );

        landmark_jp.setBorder(javax.swing.BorderFactory.createTitledBorder("Landmarks"));
        anchor_jt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "UUID", "Friendly Name", "Device Class"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        anchor_jsp.setViewportView(anchor_jt);

        jToggleButton3.setText("Remove");

        jToggleButton2.setText("Edit");

        jToggleButton1.setText("Create");

        jScrollPane1.setViewportView(jList1);

        jToggleButton4.setText("Reset");

        jLabel1.setText("Name:");

        org.jdesktop.layout.GroupLayout landmark_jpLayout = new org.jdesktop.layout.GroupLayout(landmark_jp);
        landmark_jp.setLayout(landmark_jpLayout);
        landmark_jpLayout.setHorizontalGroup(
            landmark_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(landmark_jpLayout.createSequentialGroup()
                .addContainerGap()
                .add(landmark_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(landmark_jpLayout.createSequentialGroup()
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(anchor_jsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                    .add(landmark_jpLayout.createSequentialGroup()
                        .add(jLabel1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jTextField1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton1)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton4)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jToggleButton3)))
                .addContainerGap())
        );
        landmark_jpLayout.setVerticalGroup(
            landmark_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(landmark_jpLayout.createSequentialGroup()
                .add(landmark_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(anchor_jsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(landmark_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(jToggleButton3)
                    .add(jToggleButton4)
                    .add(jToggleButton2)
                    .add(jToggleButton1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout main_jpLayout = new org.jdesktop.layout.GroupLayout(main_jp);
        main_jp.setLayout(main_jpLayout);
        main_jpLayout.setHorizontalGroup(
            main_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(landmark_jp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(anchor_jp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        main_jpLayout.setVerticalGroup(
            main_jpLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_jpLayout.createSequentialGroup()
                .add(anchor_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(landmark_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        file_jm.setText("Menu");
        loadScoutMap_jmi.setText("Load Scout Map");
        file_jm.add(loadScoutMap_jmi);

        saveScoutMap_jmi.setText("Save Scout Map");
        file_jm.add(saveScoutMap_jmi);

        menu_jmb.add(file_jm);

        language.setText("Language");
        languagePT_jmi.setText("Portugu\u00eas");
        language.add(languagePT_jmi);

        languageEN_jmi.setText("English");
        language.add(languageEN_jmi);

        menu_jmb.add(language);

        help_jm.setText("Help");
        menu_jmb.add(help_jm);

        exit_jm.setText("Exit");
        exitWithoutSave_jmi.setText("Exit");
        exit_jm.add(exitWithoutSave_jmi);

        exitWithSave_jmi.setText("Save and Exit");
        exit_jm.add(exitWithSave_jmi);

        menu_jmb.add(exit_jm);

        setJMenuBar(menu_jmb);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 610, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(main_jp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 416, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DiABluScoutView().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel anchor_jp;
    private javax.swing.JScrollPane anchor_jsp;
    private javax.swing.JTable anchor_jt;
    private javax.swing.JCheckBox automatic;
    private javax.swing.JTextField delay_jtf;
    private javax.swing.JMenuItem exitWithSave_jmi;
    private javax.swing.JMenuItem exitWithoutSave_jmi;
    private javax.swing.JMenu exit_jm;
    private javax.swing.JMenu file_jm;
    private javax.swing.JMenu help_jm;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel landmark_jp;
    private javax.swing.JMenu language;
    private javax.swing.JMenuItem languageEN_jmi;
    private javax.swing.JMenuItem languagePT_jmi;
    private javax.swing.JMenuItem loadScoutMap_jmi;
    private javax.swing.JPanel main_jp;
    private javax.swing.JMenuBar menu_jmb;
    private javax.swing.JLabel ms_jl;
    private javax.swing.JMenuItem saveScoutMap_jmi;
    private javax.swing.JToggleButton search_jb;
    // End of variables declaration//GEN-END:variables
    
}
