/*
 * MapperViewLog.java
 *
 * Created on 9 de Setembro de 2006, 15:09
 */

package citar.diablu.mapper.view.log;

/**
 *
 * @author  Nuno Rodrigues
 */
public class MapperViewLog extends javax.swing.JFrame {
    
    /** Creates new form MapperViewLog */
    public MapperViewLog() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        log_jsp = new javax.swing.JScrollPane();
        log_jtp = new javax.swing.JTextPane();
        clear_jb = new javax.swing.JButton();
        save_jb = new javax.swing.JButton();
        logDetail_jcb = new javax.swing.JComboBox();
        logDetail_jl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("DiABlu Mapper Log");
        log_jtp.setToolTipText("Outputs details of the undergoing operations");
        log_jsp.setViewportView(log_jtp);

        clear_jb.setText("Clear");

        save_jb.setText("Save");

        logDetail_jcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ALL", "SEVERE", "WARNING", "INFO", "CONFIG", "FINE", "FINER", "FINEST" }));

        logDetail_jl.setText("Log Detail:");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(log_jsp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(458, Short.MAX_VALUE)
                .add(logDetail_jl)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(logDetail_jcb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(save_jb)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(clear_jb)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(log_jsp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 476, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(clear_jb)
                    .add(save_jb)
                    .add(logDetail_jcb, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(logDetail_jl))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MapperViewLog().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear_jb;
    private javax.swing.JComboBox logDetail_jcb;
    private javax.swing.JLabel logDetail_jl;
    private javax.swing.JScrollPane log_jsp;
    private javax.swing.JTextPane log_jtp;
    private javax.swing.JButton save_jb;
    // End of variables declaration//GEN-END:variables
    
}
